### ISSUE TITLE
Robot_Toolkit: Issue with Push AreaUniformlyDistributedLoad failing

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Robot_Toolkit#116]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Is this still an issue, or can it be closed? If not, can it be clarified?

**Comment by IsakNaslundBh** [comment]
Bump @al-fisher

**Comment by al-fisher** [comment]
Thanks - will re-test

**Comment by al-fisher** [comment]
Just did a quick test - all working! I will close
