### ISSUE TITLE
Robot_Toolkit:  Materials Creator not Robust

### ISSUE THREAD

**Issue by emidio-piermarini** [BHoM/Robot_Toolkit#122]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
@emidio-piermarini do you know if this is still an issue? If so, do you mind adding description and test-file for it? If still a serious bug, I will move it up the priority list.
