### ISSUE TITLE
Robot_Toolkit: Issue with FabricatedBoxProfile

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/Robot_Toolkit#123]
Pushing BHoM objects with FabricatedBoxProfiles results in an error from the push component 'Section property is not support'. The bars is generated within robot but has no section assign to it.

**Comment by IsakNaslundBh** [comment]
Is this still an issue, or can it be closed? If not, can it be clarified? @jdarcyBHE

**Comment by jdarcyBHE** [comment]
Yes I believe it has been addressed
