### ISSUE TITLE
Pulling non "Bar" elements from Robot

### ISSUE THREAD

**Issue by Droidx1** [BHoM/Robot_Toolkit#154]
I've been trying to pull a simple stick element from Robot. However as this element is assigned the "RC Column" type the pull component throws up an error.

I've run a few tests on fresh Robot models and have found the following ;

Changing this element back to a "Simple Bar" type does not work.
Creating a new Robot file with a "Simple Bar" allows me to pull said bar with no errors. However, once I've changed this element to an "RC Column", it seems to forever stop this bar being pulled. As after changing it back to a "Simple Bar" still throws up the error seen in point 1).
So it seems that only elements which have only ever been "Simple Bars" can be pulled.
Attached is a screenshot of the error - please let me know it this is a simple fix and I've missed something.

(https://user-images.githubusercontent.com/28892348/48626670-6a2f5880-e9aa-11e8-97f3-96739bf67620.jpg)

**Comment by IsakNaslundBh** [comment]
@Droidx1 I think this issue has been fixed in a previous PR. Could you check if the issue still persists? If not, do you mind closing this issue, if issue still there, do you mind posting a testfile?
