### ISSUE TITLE
Robot_Toolkit: Push/Pull elements test

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Robot_Toolkit#155]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
Test scripts for Robot have been set up and used by @IsakNaslundBh and others for end-of-milestone testing and are quite robust, so I'm closing this issue as completed 😄
