### ISSUE TITLE
Robot_Toolkit: Read RigidLinks, LinkConstraints, LoadCombination

### ISSUE THREAD

**Issue by alexradne** [BHoM/Robot_Toolkit#167]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
Splitting up into separate issues and closing this:

RigidLinks: https://github.com/BHoM/Robot_Toolkit/issues/187
LoadCombinations: https://github.com/BHoM/Robot_Toolkit/issues/188
