### ISSUE TITLE
Robot_Toolkit: Section property material does not exist

### ISSUE THREAD

**Issue by MartinHenriksen** [BHoM/Robot_Toolkit#189]
Reading section properties from Robot fails if the material of the section does not already exist in the in the 
materials dictionary.

in 'ReadMaterial'-method the
`            IRobotCollection rMaterials = labelServer.GetMany(IRobotLabelType.I_LT_MATERIAL);
` seems to not return all materials used in the Robot file.

In the file attached 'ReadMaterial' will only return one Material: 'S355'. However, in 'ReadSectionProperties' secData.MaterialName will return any of 'S355', 'S275' or 'STEEL'.

[missingMaterial_test.zip](https://github.com/BHoM/Robot_Toolkit/files/2889613/missingMaterial_test.zip)

**Comment by MartinHenriksen** [comment]
did a bit more digging with the originator of the Robot model and it seems that the labelServer.GetMany() does in fact return all the materials used in the file!
However, the secData.MaterialName` in 'ReadSectionProperties' does not return the material actually used on the section but the _DEFAULT_ material! 

As it seems the issue stems from the Robot API I am unsure what can be done from our end..

The workaround for this is simple: change the default material for the section in the sections dialog and not in by selecting the bars and changeing material in the properties pane

**Comment by IsakNaslundBh** [comment]
Think I might have a solution to this, by doing some extra check of the material while reading both sections and bars.

Will push this up as soon as the toolkit is free.
