### ISSUE TITLE
Robot_Toolkit: Push breaks when SectionProperty is pushed

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Robot_Toolkit#224]
When one pushes the SectionProperty, any other push seems to stop working. Test file is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FRobot_Toolkit%2FRobot_Toolkit-Issue224-PushBreaksWhenSectionPropertyIsPushed).

**Comment by IsakNaslundBh** [comment]
Think this has been fixed here:
https://github.com/BHoM/Robot_Toolkit/pull/222

At least the test script is running for me. Throwing a warning that I added in the linked PR, which seem to be to a large extent a Robot-side issue that we have little control over.
![image](https://user-images.githubusercontent.com/22005920/58940533-f86a0100-8779-11e9-9dd3-2a79b833c1a4.png)

For me the bar gets pushed and has the correct section assigned:

![image](https://user-images.githubusercontent.com/22005920/58940563-0750b380-877a-11e9-8b78-4d6fd402b7c1.png)

**Comment by pawelbaran** [comment]
Right, works fine after recompiling on master. Happy to close without any action!
