### ISSUE TITLE
Robot_Toolkit: Uniform bar loads

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/Robot_Toolkit#227]
Pushing uniform bar loads into Robot both Force and Moment load items are created in Robot despite only a force vector being applied.

![image](https://user-images.githubusercontent.com/34092831/59842435-791a2700-934e-11e9-8ae8-03e5f3762d75.png)

Method should be updated to check magnitude of vectors and if zero then load item isn't created.

@IsakNaslundBh

**Comment by IsakNaslundBh** [comment]
@jdarcyBHE this should have been fixed here: https://github.com/BHoM/Robot_Toolkit/pull/225

Could you try re syncing and re-building and check if it presists?

**Comment by jdarcyBHE** [comment]
I have re built to the latest code, and your correct Isak the issue has been addressed.
