### ISSUE TITLE
Robot_Toolkit: Read load combinations

### ISSUE THREAD

**Issue by rwemay** [BHoM/Robot_Toolkit#247]
#### Description:

Load combinations read is not implemented, and the read loadcases also returns combinations which it should not. 

#### Expected behaviour:

Read combinations should return combinations, read cases should return cases.

**Comment by FredericBourgeon** [comment]
Fixed with commit 7006a03b6419047db8165cca306af9eb19d68c18

**Comment by FredericBourgeon** [comment]
Oh well, at least I hope I gave you a good laugh :smile:.
Any pointers how I can clean up this mess and eventually get (half-)decent code into codebase for next release?

**Comment by rwemay** [comment]
Hey @FredericBourgeon , looks good! Feel free to raise a Pull Request for this. A couple of initial comments: 
 - I'd probably create a new LoadCombination.cs in the Read/Loads folder for now;
 - It _might_ be faster to create a dictionary of cases by calling the read loadcase method (although that also needs to be updated so that it's not reading combinations - would be good to solve in the same PR actually). The way you have it is fine though, and still may be faster (my suggestion would require 2x pull;
 - I would add the Robot.Project.Structure.Cases.BeginMultiOperation() and .....EndMultiOperation() as this can sometimes speed up the process (also needs adding to the read loadcases). 

@IsakNaslundBh FYI

**Comment by IsakNaslundBh** [comment]
Think this can be closed now that https://github.com/BHoM/Robot_Toolkit/pull/313 has been merged? @rwemay
