### ISSUE TITLE
Pull NodeResult returns multiple mode results for seismic cases

### ISSUE THREAD

**Issue by njsmithies** [BHoM/Robot_Toolkit#261]
When pulling NodeResults for a Robot seismic case multiple modal results are returned in no particular order. Combined CQC or SRSS result is not returned. 

Pulling seismic results case should return combined  (CQC or SRSS...) result only. 

To return modal results a mode property is required in NodeResult. 

Test File: https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Robot_Toolkit/%20Robot_Toolkit-Issue%20261-Pull%20NodeResult%20Seismic%20Case?csf=1&e=Bx9RHs

**Comment by rwemay** [comment]
Thanks @njsmithies , can you also please save a copy of the model in the test script library? There is a subfolder for issues, and you can create a new folder in there with the issue number above.

**Comment by rwemay** [comment]
@IsakNaslundBh , the result class doesn't have a 'Mode' property - I think we should add, as this isn't only relevant for modal analysis results, but seismic (response spectrum analysis) too. In the interim I'm planning to make the Robot_Toolkit report results from the combined seismic results. The 'Modal' property, if there was one, in this case would return 'CQC' for all results (which is the name of the modal composition method).

**Comment by IsakNaslundBh** [comment]
@rwemay I agree. We could make use of and rename the `TimeStep` property potentially to handle this. Calling it just `Step` or similar could maybe be generic enough? Could maybe do this (add to timeStep) as a fix for now?

If not clear enough (not sure it is really..), might have to resort to add in a `Mode` property for all of our structural results, agreed.

**Comment by rwemay** [comment]
Hey @IsakNaslundBh , as Skyped, would be great to reuse an existing property, but I think in this case we'd need a specific `Mode` string property - as we'd need to store/know whether it's a time history or a modal analysis in any case, apart from mode being stored as timestep being a bit confusing. 

The only other way I thought was to create a new result class(es) specific to the analysis type, but not sure we want to go down that route......

**Comment by rwemay** [comment]
Hey @njsmithies , I've pushed an update to the branch below. I'm having internet issues as on very weak connection so I might struggle to test this today (can't get a license/open models). If you've a few mins, feel free to give it a go, but if it fails first time, wait for me to test later. @johannaisak , @JonathanNillius  FYI

**Comment by JonathanNillius** [comment]
The branch works! Thanks!
