### ISSUE TITLE
Generate property names automatically on push when the objectis OK

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Robot_Toolkit#263]
#### Description:
Currently Robot requires assigning names to virtually any property that is pushed to it. It is logical, but causes a lot of confusion on the user end: 'why is my element losing properties on push?'. Would be good to make Robot generate some names automatically, e.g. by concatenating property names etc.

#### How to replicate:
See the test file.

#### Expected behaviour:
Make it possible to push properties without names.

#### Test file(s):
Test file loaded to [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRobot%5FToolkit%2FRobot%5FToolkit%2DIssue263%2DGeneratePropertyNamesAutomatically).

**Comment by IsakNaslundBh** [comment]
Good one, and I agree. Think this need to be solved in a more central place, and issue for it raised here:

https://github.com/BHoM/BHoM_Engine/issues/820

One of the issues I hope will get resolved this quarter.

**Comment by rwemay** [comment]
Nice one!

**Comment by IsakNaslundBh** [comment]
Will be able to solved easily once https://github.com/BHoM/BHoM_Engine/issues/1398 has been done
