### ISSUE TITLE
Robot_Toolkit: Pull custom steel sections

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/Robot_Toolkit#274]
#### Description:
Currently custom type steel sections aren't support, adding search for the custom section label name against the catalogued sections to find a match would be very useful.

This would enable better workflows and improved transfer of models from Tekla into Robot 

![image](https://user-images.githubusercontent.com/34092831/67944290-06f70000-fbd4-11e9-8beb-af7578512c79.png)

**Comment by IsakNaslundBh** [comment]
@jdarcyBHE Do you have an example case for this, as a simple test file?

When pushing sections, the built in library in Robot is scanned to try to find one with a matching name. You can control which of Robots databases that is checked through in the adapter settings for Robot (which you might know already).

Currently the adapter should be creating an explicit section in robot for you as a last resort. The priority order is as follows:

1. Try to find an appropriate catalogue section in robot based on the name
1. Generate a parametric section
1. If non of the above works/is implemented, generate an explicit section.

**Comment by Martian42** [comment]
@IsakNaslundBh @jdarcyBHE please correct me if I'm wrong, link below an example file from a recent project, showing how custom data is not transported through.

Managed to 'Update property' by matching and linking the section in 'ExportScript'. I supposea script that auto-create non-standard section would be useful in this instance.

[C:\Users\msuen\BuroHappold\Buildings and Habitats object Model - 01_Test Scripts\Robot_Toolkit\Issues\Robot_Toolkit-Issue274-Pull custom steel sections](url)

**Comment by IsakNaslundBh** [comment]
Should be fixed by together with https://github.com/BHoM/Robot_Toolkit/issues/342
