### ISSUE TITLE
Robot_Toolkit: Pull Panel Area Loads

### ISSUE THREAD

**Issue by ebowyer** [BHoM/Robot_Toolkit#294]
#### Description:

Can we please have a function for pulling the area loads out of Robot from panels?  This will be really handy for several reasons, not least copying load configurations across from one model type to another especially when loads/combos are being continually updated.  

For context, I was trying to pull out the loading (into GH) and then push it into another model onto simular elements but with new geometry.  It is much quicker to redraw a slab for example entirely if there is a lot of change rather than edit an existing one.  
 @johannaisak

**Comment by ebowyer** [comment]
Hiya, have we had any progress on this as yet? thank you

**Comment by IsakNaslundBh** [comment]
Hi @ebowyer ! Good timing, this is just to be started to get looked at by @Martian42 , hopefully today, if not tomorrow or early next week.

**Comment by ebowyer** [comment]
ah okay super :) thank you

**Comment by ebowyer** [comment]
ah okay super :) thank you

**Comment by ebowyer** [comment]
ah okay super :) thank you
