### ISSUE TITLE
Robot_Toolkit: PUSH PULL ISSUES STEEL ANGLE SECTIONS

### ISSUE THREAD

**Issue by njsmithies** [BHoM/Robot_Toolkit#325]
Some standard angle properties do not exist in the BHoM UK library, existing equal angle sections can be produced from profile or library and pushed/pulled with correct name. Existing unequal angle can be produced from profile or library and pushed but pulling these sections are not supported and resulting bars have null SectionProperty. Non existing section can be produced from profile but pulling these sections are not supported and resulting bars have null SectionProperty.

When non-standard angle sections are pushed an invalid parametric element with 0 properties is generated and cannot be pulled, if manually converted to explicit section can be pushed but not pulled (see Robot_Toolkit: Pull custom steel sections #274). 

All standard UK angle sections should be included in library and be pulled and pushed as standard angle. 

Push of non standard angle section should auto-generate an explicit section (no parametric/special option in Robot section module).  A pull of non-standard section property should result in explicit section with name and mechanical properties, profile may be null. 

Test files: https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Robot_Toolkit/Issues/Robot_Toolkit-Issue324-Reference%20User%20Section%20Database?csf=1&e=xWKQWz 

@rwemay  @IsakNaslundBh @jdarcyBHE

**Comment by IsakNaslundBh** [comment]
Should be resolved together with https://github.com/BHoM/Robot_Toolkit/issues/342
