### ISSUE TITLE
Robot_Toolkit: Remove hard coded bar result parameters

### ISSUE THREAD

**Issue by rwemay** [BHoM/Robot_Toolkit#403]
#### Suggestions to restore compliance:

Remove divisions, modes etc from the result request and return an error that these need to be input explicitly.

**Comment by IsakNaslundBh** [comment]
Have put this description for other toolkits as the solution @rwemay :




#### Broken rules:


It is dangerous to pull results only specifying the type you want back. Results should only be pulled using the explicit ResultRequests.

#### Suggestions to restore compliance:


Remove support for pulling results with filter requests, and raise a warning stating what request the user should be using instead.
