### ISSUE TITLE
Rename Unit-Tests solution

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Robot_Toolkit#509]
https://github.com/BHoM/Robot_Toolkit/blob/b18343f23f042db8cf44a5aac45f400b2535957b/.ci/unit-tests/Robot_Adapter_Tests.sln#L1

Needs to be {NameOfRepo}_Tests - so should be `Robot_Toolkit_Tests.sln`

**Comment by IsakNaslundBh** [comment]
will fix.

Just solution file or csproj as well?

**Comment by FraserGreenroyd** [comment]
Sorry @IsakNaslundBh - as discussed offline, just the `sln` file - the csproj/DLLs can be any name providing then end with `_Tests.dll` and the bot can pick them up.
